### ISSUE TITLE
Installed but not showing in Kwin scripts settings

### ISSUE THREAD

**Issue by nivaca** [lingtjien/Tiling-Gaps-Kwin#1]
I just installed it locally per your instructions. However, it doesn't show in System Settings -> Window Management -> KWin Scripts.
Should it appear there?

**Comment by lingtjien** [comment]
hmm yeah it should, it basically needs a folder in /share/kwin/scripts/ which contains the contents folder and the metadata.desktop and then it needs a link or copy of the metadata.desktop in /share/kservices5 but then named "kwin-script-tiling-gaps.desktop".

But I am running on Arch, maybe it's different for other OS. The normal way to install it is to use:

plasmapkg2 --type kwinscript -i tiling-gaps

but this would not create a gear icon to access the UI for me, but you coudl try that

**Comment by nivaca** [comment]
I'm on Arch also. I deleted `~/.local/share/kwin/scripts/kpluginindex.json` and everything works now. Thanks!

**Comment by m3l7** [comment]
the settings button is hidden for me too.
I'm using arch
Tried to delete kpluginindex.json as suggested but still the button does not show up

**Comment by lingtjien** [comment]
Glad you got it working :)

(I'll do some more testing tomorrow if I have time, to check out if I can replicate any issues with the links.)

**Comment by marsch** [comment]
had problems with kali rolling - just copied the `kwin-script-grid-tiling.desktop` file to `/usr/share/kservices5` which wasn't existing in `~/.local/share` 
 - may be that helps for someone who's facing the same problem
