### ISSUE TITLE
Preview

### ISSUE THREAD

**Issue by realmain** [lingtjien/Tiling-Gaps-Kwin#2]
> Note: GitHub does not support viewing videos in the ReadMe, if you want to see an example just watch the tiling-gaps.mp4 in the preview folder

Someone could make a .gif for this and put it in the ReadMe :)

I don't know how to do it myself though.

**Comment by naund** [comment]
ffmpeg -i tiling-gaps.mp4 -vf scale=320:-1 -r 10 -f image2pipe -vcodec ppm - | convert -delay 5 -loop 0 - tiling-gaps.gif

**Comment by lingtjien** [comment]
Hmm sorry for the late response, the notification got lost in my mail I think... Anyways, yeah sure it doesn't hurt so why not
